### PR TITLE
Add darkmode to frontend

### LINKED ISSUE #258: Add darkmode to frontend
Filament (admin area) already has dark mode. Might be nice to have a dark mode feature on the frontend too.

### PR DESCRIPTION
**Pull request by fabiorodriguesroque**
closes #258

### CODE REVIEW

**Comment by Cannonb4ll** [comment]
Nice work! Let me know once it's ready to be tested 🙌

**Review by fabiorodriguesroque — COMMENTED** [review]
I need help on this, basically on comment when you select private note, this bg yellow brokes the dark mode. I'm not understanding why.

**Comment by fabiorodriguesroque** [comment]
@Cannonb4ll ready to review, I've just mentioned the problem with bg-yellow on private notes, and other thing that I want to ask you is, this PR doesn't include any button to switch mode, but it's sycned with filament panel, should I create a toggle for public view? 

Thanks.

**Comment by Cannonb4ll** [comment]
Nice work! Excellent💙

Yes, a toggle button on the frontend would be very welcome if possible.

Otherwise, I can add that later too💪

**Comment by fabiorodriguesroque** [comment]
@Cannonb4ll toggle added to public view!

**Comment by Cannonb4ll** [comment]
Works beautifully 🙌 Thank you so much! 😍

**Pull request merged**
