### PR TITLE
added the url to the item column of the recent-comments widget

### PR DESCRIPTION
**Pull request by lao9s**
It's useful to open the item while you read the recent comments.

### CODE REVIEW

**Review by SebastiaanKloos — CHANGES_REQUESTED** [review]
I would suggest to make the whole row clickable instead of only one column. What do you think @Cannonb4ll ?

**Comment by lao9s** [comment]
> I would suggest to make the whole row clickable instead of only one column. What do you think @Cannonb4ll ?

No problem. Have to wait for confirmation from @Cannonb4ll ?

**Comment by Cannonb4ll** [comment]
No need to wait @lao9s! Would indeed be nice if you can make the whole table row clickable, and also include the comment hash so it lights up (`#comment-{id}`), an example:

https://roadmap.ploi.io/items/15-ability-to-clone-entire-server#comment-135

**Comment by lao9s** [comment]
@Cannonb4ll Done

**Review by Cannonb4ll — APPROVED** [review]

**Comment by Cannonb4ll** [comment]
@SebastiaanKloos Can you leave your review for this? Seems good to me.

**Comment by Cannonb4ll** [comment]
Awesome, thanks! 💙

**Pull request merged**
