### PR TITLE
Notification translations NL

### PR DESCRIPTION
**Pull request by ndijkstra**

### CODE REVIEW

**Comment by Cannonb4ll** [comment]
This is not going to work if you use a queue driver (e.g. not using `sync` as driver).

You'll always need to specify the locale on the mailable/notification to make sure it will use that locale:

https://laravel.com/docs/9.x/mail#localizing-mailables

**Comment by ndijkstra** [comment]
I don't have issues in another Laravel app with this in combination with queueing.

> Laravel allows you to send mailables in a locale other than the request's current locale, and will even remember this locale if the mail is queued.
The Laravel docs say you have to specify the locale if you want to send it in an other locale than the request, right?

**Comment by ndijkstra** [comment]
Just tested it locally, but after it got queued the notification is sent in the language as specified in the .env

**Comment by Cannonb4ll** [comment]
@ndijkstra Ah then I've missed that update, then once you queue the mail, it will probably take a look at the app locale at that point and remember it inside the serialized job. Good call, and thanks for testing it as well.

**Pull request merged**
