### PR TITLE
Upgrade to Laravel 10

### PR DESCRIPTION
**Pull request by Cannonb4ll**

### CODE REVIEW

**Review by SebastiaanKloos — APPROVED** [review]
I don't see anything special. Should be okay if the tests pass right?

**Comment by Cannonb4ll** [comment]
I agree, works fine in my local environment. Just waiting for @ndijkstra's confirmation.

**Comment by SebastiaanKloos** [comment]
> I agree, works fine in my local environment. Just waiting for @ndijkstra's confirmation.

Just to be sure. Did you also test it with Postgres? 👀

**Review by ndijkstra — APPROVED** [review]
Looks good

**Pull request merged**
